export const BIRD_NAMES = [
  'Choco Tinamou',
  'West Indian Whistling-Duck',
  'Taiga Bean-Goose',
  'Pink-footed Goose',
  'Atlantic Brant',
  'Trumpeter Swan',
  'Wood Duck',
  'American Wigeon',
  'American Black Duck',
  'Cinnamon Teal',
  'Unidentified Teal',
  'Northern Shoveler',
  'White-cheeked Pintail',
  'Tufted Duck',
  'Banded Quail',
  'Crested Bobwhite',
  'Marbled Wood-Quail',
  'Gray Partridge',
  'Reddish Egret',
  'Green Heron',
  'Yellow-footed Gull',
  'Barn Owl',
  'Blue-capped Hummingbird',
  'Red-bellied Woodpecker',
  'Black-chested Jay',
  'Green Jay',
  'Red-winged Blackbird',
];
