name: Bump version
on:
  workflow_dispatch:
    branches: [ master ]
    inputs:
      bumpLevel:
        description: 'Bump level (major, minor, or patch)'
        required: true
        default: 'minor'

defaults:
  run:
    working-directory: ./client

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fregante/setup-git-user@v1
    - name: Bump version
      env:
        BUMP_LEVEL: ${{ github.event.inputs.bumpLevel }}
      run: yarn version --"${BUMP_LEVEL}"
    - name: Push commit
      run: git push
