name: Cedar client workflow

on: [push]

defaults:
  run:
    working-directory: ./client

jobs:
  #test-client:

    #runs-on: ubuntu-latest

    #steps:
    #- uses: actions/checkout@v2
    #- name: Use Node.js 14.x
      #uses: actions/setup-node@v1
      #with:
        #node-version: 14.x
    ## NOTE(gnewman): Puzzlingly, we need to install the api dependencies as
    ## well to get the build step to work. My suspicion is that there is some
    ## gap in the type system that causes TypeScript to treat a type as
    ## "unknown" that shouldn't be/isn't unknown, but I haven't nailed down the
    ## root cause. For now, this gets us by.
    #- run: cd ../api && yarn install
    #- run: yarn install
    #- run: yarn build
    ## TODO(gnewman): Remove --passWithNoTests flag when we add our first test
    #- run: yarn test --passWithNoTests
    #- uses: actions/upload-artifact@v2
      #with:
        #name: build-files
        #path: ./client/build

  draft-mac-client-release-if-version-bumped:

    #needs: test-client

    #if: contains(github.ref, 'bump-v')

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: cd ../api && yarn install
    - run: yarn install
    - run: yarn build
    - name: Build Cedar for Mac
      env:
        APPLEID: ${{ secrets.APPLEID }}
        APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
        CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        CSC_LINK: ${{ secrets.CSC_LINK }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: yarn build-electron-app --mac --publish always

  draft-windows-client-release-if-version-bumped:

    #needs: test-client

    #if: contains(github.ref, 'bump-v')

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: cd ../api && yarn install
    - run: yarn install
    - run: yarn build-windows
    - name: Build Cedar for Windows
      env:
        CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        CSC_LINK: ${{ secrets.CSC_LINK }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
        WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
      run: yarn build-electron-app --win --publish always
