name: Cedar client tests

on: [push]

defaults:
  run:
    working-directory: ./client

jobs:
  test-client:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    # NOTE(gnewman): Puzzlingly, we need to install the api dependencies as
    # well to get the build step to work. My suspicion is that there is some
    # gap in the type system that causes TypeScript to treat a type as
    # "unknown" that shouldn't be/isn't unknown, but I haven't nailed down the
    # root cause. For now, this gets us by.
    - run: cd ../api && yarn install
    - run: yarn install
    - run: yarn build
    # TODO(gnewman): Remove --passWithNoTests flag when we add our first test
    - run: yarn test --passWithNoTests
