name: Cedar client tests

on: [push]

defaults:
  run:
    working-directory: ./client

jobs:
  test-client:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn install
    - run: yarn build
    - run: yarn test
